on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Docker Login
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.AZURE_URL }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - name: Build and push container image to registry
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: latest
            file: "Dockerfile"
